// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
)

type User struct {
	Uuid         uuid.UUID `json:"uuid"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}
