// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const blacklistToken = `-- name: BlacklistToken :exec
UPDATE tokens SET status='blacklisted', expires_at=NOW()  WHERE uuid=$1
`

func (q *Queries) BlacklistToken(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, blacklistToken, argUuid)
	return err
}

const blacklistTokenFamily = `-- name: BlacklistTokenFamily :exec
UPDATE token_families SET status='blacklisted' WHERE uuid=$1
`

func (q *Queries) BlacklistTokenFamily(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, blacklistTokenFamily, argUuid)
	return err
}

const createToken = `-- name: CreateToken :one

INSERT INTO tokens(family, hash) VALUES($1, $2)
RETURNING id, hash, uuid, created_at, expires_at, family, status
`

type CreateTokenParams struct {
	Family uuid.UUID `json:"family"`
	Hash   string    `json:"hash"`
}

// -------------------------------------------
// INSERT QUERIES
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken, arg.Family, arg.Hash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Uuid,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Family,
		&i.Status,
	)
	return i, err
}

const createTokenFamily = `-- name: CreateTokenFamily :one
INSERT INTO token_families(user_uuid) VALUES($1)
RETURNING id, uuid, user_uuid, status
`

func (q *Queries) CreateTokenFamily(ctx context.Context, userUuid uuid.UUID) (TokenFamily, error) {
	row := q.db.QueryRow(ctx, createTokenFamily, userUuid)
	var i TokenFamily
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserUuid,
		&i.Status,
	)
	return i, err
}

const deleteTokenByHash = `-- name: DeleteTokenByHash :exec

DELETE FROM tokens WHERE hash = $1
`

// -------------------------------------------
// DELETE QUERIES
func (q *Queries) DeleteTokenByHash(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteTokenByHash, hash)
	return err
}

const deleteTokensByFamily = `-- name: DeleteTokensByFamily :exec
DELETE FROM tokens WHERE family = $1
`

func (q *Queries) DeleteTokensByFamily(ctx context.Context, family uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTokensByFamily, family)
	return err
}

const discardToken = `-- name: DiscardToken :exec
UPDATE tokens SET status='used', expires_at=NOW() WHERE uuid=$1
`

// UPDATE QUERIES
func (q *Queries) DiscardToken(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, discardToken, argUuid)
	return err
}

const getTokenByHash = `-- name: GetTokenByHash :one

SELECT id, hash, uuid, created_at, expires_at, family, status FROM tokens WHERE hash = $1
`

// -------------------------------------------
// GET QUERIES
func (q *Queries) GetTokenByHash(ctx context.Context, hash string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, hash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Uuid,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Family,
		&i.Status,
	)
	return i, err
}

const getTokenFamilyByUUID = `-- name: GetTokenFamilyByUUID :one
SELECT id, uuid, user_uuid, status FROM token_families WHERE uuid=$1
`

func (q *Queries) GetTokenFamilyByUUID(ctx context.Context, argUuid uuid.UUID) (TokenFamily, error) {
	row := q.db.QueryRow(ctx, getTokenFamilyByUUID, argUuid)
	var i TokenFamily
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserUuid,
		&i.Status,
	)
	return i, err
}
