// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAdminData = `-- name: GetAdminData :one
SELECT u.email, u.uuid, u.role FROM admins a
JOIN user_public_data u on u.UUID=a.uuid
WHERE a.user_uuid=$1
`

func (q *Queries) GetAdminData(ctx context.Context, userUuid uuid.UUID) (UserPublicDatum, error) {
	row := q.db.QueryRow(ctx, getAdminData, userUuid)
	var i UserPublicDatum
	err := row.Scan(&i.Email, &i.Uuid, &i.Role)
	return i, err
}

const getStandardData = `-- name: GetStandardData :one
SELECT  u.email, u.uuid, u.role FROM standards s
JOIN user_public_data u on u.uuid=s.uuid
WHERE s.user_uuid=$1
`

func (q *Queries) GetStandardData(ctx context.Context, userUuid uuid.UUID) (UserPublicDatum, error) {
	row := q.db.QueryRow(ctx, getStandardData, userUuid)
	var i UserPublicDatum
	err := row.Scan(&i.Email, &i.Uuid, &i.Role)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uuid, password_hash FROM users WHERE email=$1
`

type GetUserByEmailRow struct {
	Uuid         uuid.UUID `json:"uuid"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.Uuid, &i.PasswordHash)
	return i, err
}

const getUserDataByUUID = `-- name: GetUserDataByUUID :one
SELECT email, uuid, role FROM user_public_data WHERE uuid=$1
`

func (q *Queries) GetUserDataByUUID(ctx context.Context, argUuid uuid.UUID) (UserPublicDatum, error) {
	row := q.db.QueryRow(ctx, getUserDataByUUID, argUuid)
	var i UserPublicDatum
	err := row.Scan(&i.Email, &i.Uuid, &i.Role)
	return i, err
}

const newAdmin = `-- name: NewAdmin :exec
INSERT INTO admins (user_uuid) VALUES ($1)
`

func (q *Queries) NewAdmin(ctx context.Context, userUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, newAdmin, userUuid)
	return err
}

const newStandard = `-- name: NewStandard :exec
INSERT INTO standards (user_uuid) VALUES ($1)
`

func (q *Queries) NewStandard(ctx context.Context, userUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, newStandard, userUuid)
	return err
}

const newUser = `-- name: NewUser :one
INSERT INTO users (email, password_hash, role) VALUES($1, $2, $3)
RETURNING uuid, email, password_hash, role
`

type NewUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         Role   `json:"role"`
}

func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) (User, error) {
	row := q.db.QueryRow(ctx, newUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}
